### ISSUE TITLE
v0.9 Release checklist

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/polyproto#36]
After a solid 1? 2? months of development, v0.9 of the polyproto crate is almost ready. v0.9 is, by far, the biggest update yet. It fixes countless oversights made in previous releases which were now caught through testing, documenting and rigorous reviewing of my code, adds a plethora of new features, such as a full polyproto HTTP client, contextual and better validation of certificates and other types and many, many more things.

This issue documents the last few things that have to be implemented or changed, before I am truly happy with this update.

## Missing routes (including tests)

- [x] GET Encrypted private key material
- [x] POST Encrypted private key material
- [x] DELETE Encrypted private key material
- [x] OPTIONS: Get max upload size of private key material

## General

- [x] Review open TODOs
- [x] Re-read documentation, check for needed updates

## Examples

- [x] Provide examples for how to use the HTTP client
- [x] Perhaps re-organize the examples into their own crate, similar to how some other projects do it
- [x] Add validation of certificates to examples
