### ISSUE TITLE
"Migrations" tracking issue

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/polyproto#38]
Tracking issue for integration section #7 "Migrations" into the polyproto crate. This does not only involve implementation of routes, but the API design for the routes as well.

## Identity migration

- [ ] Setting up a redirect
- [ ] Handle HTTP 307/308 status codes for routes, which request information about or send information to another actor, if this is needed

## Re-signing messages

This might be a hard one. The protocol specification currently does not define a fixed schema for message re-signing batches.

- [ ] Handshake procedure
- [ ] Change ownership of messages signed by certain keys
- [ ] Change ownership of messages signed by all available keys
- [ ] Reduce amount of keys that need to be remembered
- [ ] "Rotate keys of past messages"

## Moving data

- [ ] APIs for exporting data -> Protocol spec additions needed?
- [ ] APIs for importing data

## Challenges and trust

- [ ] Verify challenge validity for challenges that involve migration -> Section 7.4 of the protocol
