### ISSUE TITLE
"Services and Discoverability" tracking issue

### ISSUE THREAD

**Issue by bitfl0wer** [polyphony-chat/polyproto#39]
Issue to track the addition of elements found in section 9 "Services" of the specification into the polyproto crate. This does not only include the implementation of the API routes, but the designing of them as well.

## Discoverability

- [x] Add service to be discovered
- [x] Set primary service provider
- [x] Remove service to be discovered
- [x] Discover services of user
- [x] Discover singular service of user
~~- [ ] Optional: Privacy routes~~

**Comment by bitfl0wer** [comment]
Included in the v0.10 branch.
